### ISSUE TITLE
Getting weird bugs with `:PaqClean`

### ISSUE THREAD

**Issue by evantravers** [savq/paq-nvim#23]
I'm trying to figure out how to replicate, but every once in a while, I'll run `:PaqClean`, and it'll delete a _ton_ of plugins that are still declared in my init.lua. Sometimes it'll even delete paq.nvim.

When this happens… `:PaqInstall` won't install everything either… I have to keep closing vim and re-running the install command until everything is installed.

I'll keep working on replicating it reliably.

https://github.com/evantravers/dotfiles/tree/nightfly

**Comment by savq** [comment]
Yep. There was a bug in v0.6.2. I pushed a patch a couple of hours before this issue. Hopefully when you downloaded paq again, it was the new version.

I'll keep this open for a couple of days to be completely sure that everything is working correctly.

`:PaqInstall` should be working fine though. If plugins weren't installed properly, the plugins probably weren't deleted properly and there are residual directories that cause `git clone` to fail.

**Comment by evantravers** [comment]
I tried burning the folders to try and force Paq to install everything… but I'm still getting false numbers `[1/3]` to start with, then the next time I restart I'm getting `[3/12]` and I get the next batch… I assume I'm doing something wrong, but it's weird.

**Comment by evantravers** [comment]
![image](https://user-images.githubusercontent.com/62209/109317639-88839000-7812-11eb-9191-87acc6abf3dd.png)

**Comment by evantravers** [comment]
I think part of the problem may be that I have killed nvim before it's done cloning it's current batch… there's a folder and repo, but it hasn't finished pulling/rebasing.

**Comment by savq** [comment]
Ok, the screenshot made it easy to see one of the problems. That's likely fixed now.

The message in the log is probably unrelated though 🤔

**Comment by evantravers** [comment]
I'm sure I'm doing something dumb… potentially my `git config` or `$XDG_DATA_HOME`? Unsure.

https://asciinema.org/a/mhiJAkIaNMsST7Wzp5xw0bes8

☝️ There's a recording of the incremental saving occurring… am I just following a bad practice with my [nvim.lua](https://github.com/evantravers/dotfiles/blob/master/nvim/.config/nvim/init.lua)?

**Comment by savq** [comment]
Ahh, ok, the problem isn't that bad.

What's happening is that Neovim will raise an error when it gets to line 18 of your dotfiles, where you're defining your colorscheme. Neovim can't find it (since it isn't installed yet). When you enter Neovim again, it'll get to line 22, where there's a require call, etc.

I hadn't noticed because I source all my plugins at the top of my config, but you can still use your plugins as you have them now. It just needs a little bootstrapping.


**Lazy solution:**

Create a temporary file with a list of the plugins, install all of them, and then use your dotfiles as usual.

```sh
cd ~/.config/nvim/
cat init.lua | grep 'paq' > temp.lua
nvim -u temp.lua
```

The `-u` flag tells Neovim to use a different initialization file, once in Neovim you should be able to run `:PaqInstall` without issues.

**Comment by evantravers** [comment]
Thanks @savq. I believe that was it… I knew I was doing something odd. I just moved everything to the top of the file for now, and everything is golden.

I may try to some lua magic where I register a plugin and it's config and at the end require all the plugins and setup all the config… but that can wait.

https://github.com/evantravers/dotfiles/commit/0ea49e06fc87872c518bd96334a2d4ff63367d4b

**Comment by savq** [comment]
No problem, I'm glad I could help. and sorry for the other inconveniences.
